### ISSUE TITLE
Testimonial

### ISSUE THREAD

**Issue by dajinchu** [sandboxneu/sandboxneu.com#24]
We have a some amazing testimonial material. Let's include it somehow in the landing page. It's very persuasive for researchers to work with us, and shows students that we're not messing around.

**Comment by klu17** [comment]
Is the testimonial material available in a Google doc?

**Comment by ryandrew14** [comment]
@klu17 I think this is actually closed by #30 -- it's on our website at the bottom of the landing page. I don't know if we have any testimonial material currently other than that.
